# Generated by Django 3.0.5 on 2020-05-05 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expediente',
            options={'verbose_name': 'Expediente', 'verbose_name_plural': 'Expedientes'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='personalhospital',
            options={'verbose_name': 'Personal Medico', 'verbose_name_plural': 'Personal Medico'},
        ),
    ]
