# Generated by Django 3.0.5 on 2020-05-15 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0002_auto_20200504_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expediente',
            old_name='numSeguro',
            new_name='Paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='numDoctor',
            new_name='Doctor',
        ),
        migrations.AddField(
            model_name='personalhospital',
            name='User',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='diagnostico',
            field=models.CharField(help_text='Diagnostico del medico:', max_length=600, verbose_name='Diagnostico'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='enfermedad',
            field=models.CharField(help_text='Enfermedades que presenta el paciente:', max_length=600, verbose_name='Enfermedad'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='exploracionFisica',
            field=models.CharField(help_text='Resultado de la revision fisica del paciente:', max_length=600, verbose_name='Exploracion fisica'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='planTratamiento',
            field=models.CharField(help_text='Plan asignado para atender al paciente:', max_length=600, verbose_name='Plan de tratamiento'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='pronostico',
            field=models.CharField(help_text='Pronostico de recuperacion:', max_length=600, verbose_name='Pronostico'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='resultadosEstudios',
            field=models.CharField(help_text='Resultados de los estudios practicados:', max_length=600, verbose_name='Resultados de los estudios'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='resumenInterrogatorio',
            field=models.CharField(help_text='Resumen del interregotario medico:', max_length=600, verbose_name='Resumen del interrogatorio'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='signosVitales',
            field=models.CharField(help_text='Signos vitales del paciente:', max_length=200, verbose_name='Signos vitales'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellidoPPa',
            field=models.CharField(max_length=30, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccionPa',
            field=models.CharField(help_text='Ingrese la direccion:', max_length=50, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fechaIng',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fechaNaPa',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='habitacion',
            field=models.CharField(help_text='Ingrese la habitacion:', max_length=4, verbose_name='Habitacion'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombrePa',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numSeguro',
            field=models.IntegerField(verbose_name='Numero de seguro'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numTelPa',
            field=models.IntegerField(help_text='Ingrese su numero telefonico:', verbose_name='Numero de telefono'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexoPa',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], help_text='Ingrese el sexo:', max_length=20, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='personalhospital',
            name='apellidoPPH',
            field=models.CharField(help_text='Ingrese el apellido:', max_length=30, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='personalhospital',
            name='direccionPH',
            field=models.CharField(help_text='Ingrese la direccion:', max_length=50, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='personalhospital',
            name='fechaNaPH',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='personalhospital',
            name='nombrePH',
            field=models.CharField(help_text='Ingrese el nombre:', max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='personalhospital',
            name='numMatricula',
            field=models.IntegerField(help_text='Ingrese la matricula:', verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='personalhospital',
            name='numTelPH',
            field=models.IntegerField(help_text='Ingrese su numero telefonico:', verbose_name='Numero de telefono'),
        ),
        migrations.AlterField(
            model_name='personalhospital',
            name='sexoPH',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], help_text='Ingrese el sexo:', max_length=20, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='personalhospital',
            name='tipoPH',
            field=models.CharField(choices=[('Personal_Medico', (('general', 'General'), ('especialista', 'Especialista'), ('cirujano', 'Cirujano'), ('diagnostico', 'Diagnostico'))), ('Personal_Administrativo', (('secretaria', 'Secretaria'), ('archivista', 'Archivista'), ('almacenista', 'Almacenista'), ('oficinista', 'Oficinista'))), ('Personal_Paramedico', (('enfermero', 'Enfermero'),))], help_text='Ingrese tipo de empleado:', max_length=20, verbose_name='Tipo de empleado'),
        ),
    ]
